//QUESTO OGGETTO SERVE A FARE IN MODO CHE OGNI GENERATOR
//ALLA FINE DEL TURNO VENGA "DISTRUTTO". 
//MECCANISCMO UGUALE A QUELLO DEL BULLET PARENT.


global.playerMoveTimer = 65;

//ORIGINI DEL BOX
global.boxOriginX = 160;
global.boxOriginY = 100;