face = "";
timer = 1;
firstImageAngle = image_angle;
targetX = 0;
targetY = 0;
reached = false;
cannonPower = 0;
image_speed = 0;
rotations = 15;
finalDegree = 360 * rotations;
rotationSpd = 60;
timer = 20;
actualTimer = 20;
goBackTimer = 20;
actualGoBackTimer = 20;
audio_play_sound(blaster_reloading, 50, false);